# Generated by Django 4.1.6 on 2023-02-08 07:55

import card.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_card', models.CharField(max_length=10, verbose_name='Серия карты')),
                ('number_card', models.IntegerField(verbose_name='Номер карты')),
                ('date_start_card', models.DateTimeField(auto_now_add=True, verbose_name='Дата активации карты')),
                ('date_end_active_card', models.DateTimeField(default=card.models.get_end_active, verbose_name='Дата окончания действия карты')),
                ('date_last_use_card', models.DateTimeField(auto_now=True, verbose_name='Дата последнего использования карты')),
                ('sum_purchase', models.FloatField(verbose_name='Сумма покупок')),
                ('status_card', models.CharField(choices=[('A', 'Active'), ('N', 'Not active'), ('O', 'Overdue')], default='A', max_length=1, verbose_name='Статус карты')),
                ('card_discount', models.FloatField(verbose_name='Текущая скидка')),
            ],
            options={
                'verbose_name': 'Дисконтная карта',
                'verbose_name_plural': 'Дисконтные карты',
                'ordering': ['-date_start_card'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_order', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('sum_order', models.FloatField(verbose_name='Сумма заказа')),
                ('discount_order', models.FloatField(verbose_name='Скидка')),
                ('final_cost_order', models.FloatField(verbose_name='Финальная цена')),
                ('name_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='card.card', verbose_name='Карта скидок')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date_time_order'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_goods', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('cost_goods', models.FloatField(verbose_name='Стоимость товара')),
                ('discount_cost', models.FloatField(verbose_name='Финальная цена с учетом скидки')),
                ('goods', models.ManyToManyField(blank=True, null=True, to='card.orders', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
