# Generated by Django 4.1.6 on 2023-02-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods',
        ),
        migrations.AddField(
            model_name='orders',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='card.goods', verbose_name='Заказ'),
        ),
        migrations.RemoveField(
            model_name='orders',
            name='name_card',
        ),
        migrations.AddField(
            model_name='orders',
            name='name_card',
            field=models.ManyToManyField(blank=True, null=True, to='card.card', verbose_name='Карта скидок'),
        ),
    ]
