# Generated by Django 4.1.6 on 2023-02-10 07:12

import card.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_remove_goods_goods_orders_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_card', models.CharField(max_length=10, verbose_name='Серия карты')),
                ('number_card', models.IntegerField(verbose_name='Номер карты')),
                ('date_start_card', models.DateTimeField(verbose_name='Дата активации карты')),
                ('date_end_active_card', models.DateTimeField(verbose_name='Дата окончания действия карты')),
                ('date_last_use_card', models.DateTimeField(verbose_name='Дата последнего использования карты')),
                ('sum_purchase', models.FloatField(verbose_name='Сумма покупок')),
                ('status_card', models.CharField(max_length=1, verbose_name='Статус карты')),
                ('card_discount', models.FloatField(verbose_name='Текущая скидка')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.AlterField(
            model_name='card',
            name='card_discount',
            field=models.FloatField(default=0, verbose_name='Текущая скидка'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_last_use_card',
            field=models.DateTimeField(default=card.models.new_time, verbose_name='Дата последнего использования карты'),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_start_card',
            field=models.DateTimeField(default=card.models.new_time, verbose_name='Дата активации карты'),
        ),
        migrations.AlterField(
            model_name='card',
            name='sum_purchase',
            field=models.FloatField(default=0, verbose_name='Сумма покупок'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='name_card',
            field=models.ManyToManyField(blank=True, null=True, related_name='cards', to='card.card', verbose_name='Карта скидок'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='card.goods', verbose_name='Товар'),
        ),
    ]
